-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ==============================================================================

hl.window_rule({ name = "float_pavucontrol", match = { class = "^(pavucontrol)$" }, float = true })
hl.window_rule({ name = "float_blueman", match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ name = "float_nmconnection", match = { class = "^(nm-connection-editor)$" }, float = true })
hl.window_rule({ name = "float_zenity", match = { class = "^(zenity)$" }, float = true })
hl.window_rule({ name = "float_thunar", match = { class = "^(thunar)$" }, float = true })

hl.window_rule({ name = "opacity_kitty", match = { class = "^(kitty)$" }, opacity = "0.95 0.85" })
hl.window_rule({ name = "opacity_thunar", match = { class = "^(thunar)$" }, opacity = "0.95 0.85" })

-- ==============================================================================

--   LAYER RULES  

-- ==============================================================================

hl.layer_rule({ match = { namespace = "rofi" }, blur = true, ignore_alpha = 0.4 })
hl.layer_rule({ match = { namespace = "wofi" }, blur = true, ignore_alpha = 0.4 })

